### PR TITLE
Update README URLs based on HTTP redirects

### PR DESCRIPTION
**Pull request by ReadmeCritic**
Created with https://github.com/dkhamsing/frankenstein
### GitHub Corrected URLs

| Was | Now |
| --- | --- |
| https://github.com/alexarchambault/ammonite-shell | https://github.com/alexarchambault/ammonium |
### Other Corrected URLs

| Was | Now |
| --- | --- |
| http://continuum.io/downloads | https://www.continuum.io/downloads |

### CODE REVIEW

**Comment by alexarchambault** [comment]
Thanks @ReadmeCritic 

I'm delaying merging this, as the README is in the midst of being updated.

**Comment by ReadmeCritic** [comment]
ok

**Comment by alexarchambault** [comment]
@ReadmeCritic Are you a bot btw ? :-)

**Comment by ReadmeCritic** [comment]
🤖

**Comment by ReadmeCritic** [comment]
jk

**Comment by alexarchambault** [comment]
Closing as the README changed quite a bit already. All links are now `https`, except those that can't be switched to it.

**Pull request closed without merging**
